name: Deploy to GitHub Pages

# Run workflow on every push to the main branch
on:
  push:
    branches: [main]

jobs:
  deploy-to-github-pages:
    # use ubuntu-latest image to run steps on
    runs-on: ubuntu-latest
    steps:
    # uses GitHub's checkout action to checkout code from the main branch
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    # publishes Blazor project to the release folder
    - name: Publish .NET Project
      run: dotnet publish MudBlocks\/MudBlocks.csproj -c Release -o release --nologo
    
    # lists the contents of the release folder
    - name: List directory contents
      run: ls -R release

    # changes the base-tag in index.html from '/' to 'MudBlocks' to match GitHub Pages repository subdirectory
    - name: Change base-tag in index.html from / to MudBlocks
      run: sed -i 's/<base href="\/" \/>/<base href="\/MudBlocks\/" \/>/g' release/wwwroot/index.html

    # changes the base-tag in index.html from '/' to 'MudBlocks' to match GitHub Pages repository subdirectory
    - name: Change blazor.web.js in index.html to blazor.webassembly.js
      run: sed -i 's/<script src="_framework\/blazor.web.js">/<script src="_framework\/blazor.webassembly.js">/g' release/wwwroot/index.html

    # copy index.html to 404.html to serve the same file when a file is not found
    - name: copy index.html to 404.html
      run: cp release/wwwroot/index.html release/wwwroot/404.html

    # add .nojekyll file to tell GitHub pages to not treat this as a Jekyll project. (Allow files and folders starting with an underscore)
    - name: Add .nojekyll file
      run: touch release/wwwroot/.nojekyll

    # publishes wwwroot directory to GitHub Pages
    - name: Commit wwwroot to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@4.1.5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages # The branch the action should deploy to.
        folder: release/wwwroot # The folder the action should deploy.